import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Headers/header";
import ThemeLayout from "@/components/Themebtn/themeLayout";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} dark:bg-[#1A1C29] transition duration-500`}>
          <ThemeLayout>
            <Header />
            {children}
          </ThemeLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}
